### ISSUE TITLE
Split versions

### ISSUE THREAD

**Issue by klensy** [gszabi99/War-Thunder-Datamine#1]
Hi.
Split prod\dev to different branches, as its hard to see diffs in one branch when they mixed.
Tag versions, so you can compare releases directly, for example https://github.com/klensy/wt-tools/compare/v0.2.2.3...v0.2.2.4

**Comment by gszabi99** [comment]
Sorry, by prod you mean the live client? I'm not sure what you mean. Only the dev client's updates are uploaded here, so with what are they mixed?

**Comment by VitaliiAndreev** [comment]
I reckon it's situations like this that cause complications when checking diffs.

![изображение](https://user-images.githubusercontent.com/41145853/82960176-01bb3180-9fba-11ea-8b4f-968e7a31bc4e.png)

I used to do revert commits before pushing actual patch changes to maintain change set consistency when I had branch resets for whatever reason.

![изображение](https://user-images.githubusercontent.com/41145853/82960430-c66d3280-9fba-11ea-8026-4f1995fcb2a6.png)

But I do like the tag approach more. Though it's a bit more of a fuss when everything's in order, which can be alleviated with a bit of automation.

![изображение](https://user-images.githubusercontent.com/41145853/82960452-d9800280-9fba-11ea-9dd5-4c29dbb31bb5.png)

**Comment by gszabi99** [comment]
Currently these are the git commands I use to automatically push stuff to Github.
https://github.com/gszabi99/War-Thunder-Datamine/blob/master/2-click%20git.sh
```
#!/bin/bash
VER=`cat D:/WarThunder/datamine/char.vromfs.bin_u/version`
git add .
git commit -am "$VER"
git push
```
How could I modify this to also make tags and assign them to the commits?

**Comment by VitaliiAndreev** [comment]
Try

```
git tag $VER
git push origin $VER
```

That should tag the current state of the repo, i.e. the latest commit, and push to GitHub (assuming your local repo uses the "origin" alias for the remote repo).

You can find more info [here](https://git-scm.com/book/en/v2/Git-Basics-Tagging).

**Comment by gszabi99** [comment]
How/where can I check the name? In any case, I assume "origin" is the default one?

**Comment by VitaliiAndreev** [comment]
```git remote -v```

It will be "origin" unless you specifically changed it. You might have to if you have several remotes to push to - in which case, add more lines.

**Comment by gszabi99** [comment]
```
D:\WarThunder\datamine\GitHub repo\War-Thunder-Datamine>git remote -v
origin  https://github.com/gszabi99/War-Thunder-Datamine.git (fetch)
origin  https://github.com/gszabi99/War-Thunder-Datamine.git (push)
```
Thank you, so it's origin in my case.
> You might have to if you have several remotes to push to
Is a "remote" a local copy of the branch that is on my PC?

**Comment by VitaliiAndreev** [comment]
It's what it says on the tin - a remote repository, i.e. not near you. In your case it's on GitHub (https://github.com/gszabi99/War-Thunder-Datamine.git). What you have locally is, well, a local repository only users on your machine can work with. Somebody else can fork your remote into a new remote, or clone it as a local repository. Local repositories need to be synced with their remotes to stay up-to-date if there's more than one contributor.

If you create a repo on, say, BitBucket, you might need to push to both to keep them both updated. Some sites (like GitLab) have a mirroring functionality that nicks any new commits from a specific remote.

The local-remote model applies to branches the same way it does to repositories.

**Comment by gszabi99** [comment]
Thank you for the lengthy explanation. So I believe the example you gave here is going to work for me, as I only upload them to GitHub and I'm the sole contributor.
> ```
> git tag $VER
> git push origin $VER
> ```

**Comment by VitaliiAndreev** [comment]
You're still going to need the version number, but the script that you've got already covers it.

**Comment by klensy** [comment]
Strange, in [1.99.0.21](https://github.com/gszabi99/War-Thunder-Datamine/releases/tag/1.99.0.21) something triggered rebuilding all your png files. I checked few source ddsx - they didn't changed at all.

**Comment by gszabi99** [comment]
Yes, I was perplexed as well. I have no idea what caused it, we shall see if it's also going to happen next time.

**Comment by klensy** [comment]
Only thing that changed in pngs (not source ddsx) is create and modify ext info. I've saw this few times in your repository. Try to change your dds to png convertor to not to write this info.

**Comment by gszabi99** [comment]
I use ImageMagick's mogrify tool, and I don't think I have such an option.

**Comment by klensy** [comment]
try `-define png:exclude-chunk=date `

**Comment by klensy** [comment]
You tried that IM option? It works.
Master branch without latest commits, try to add `git push origin master` after last line, maybe it will fix this issue.
It's fun: you wrote about romanian eula, but it absent from commit history, check @VitaliiAndreev repo for example.

**Comment by gszabi99** [comment]
Nope, it doesn't want to work. Many dds files were not converted by this, while with the `-format png` I used earlier, they were. For example the entirety of the atlases/medals and atlases/units folders remained dds.

**Comment by klensy** [comment]
Didn't remove `-format png`, just add that line.

**Comment by gszabi99** [comment]
Same result with `-format png -define png:exclude-chunk=date`. Lots of missing pngs.

**Comment by gszabi99** [comment]
> You tried that IM option? It works.
> Master branch without latest commits, try to add `git push origin master` after last line, maybe it will fix this issue.
> It's fun: you wrote about romanian eula, but it absent from commit history, check @VitaliiAndreev repo for example.

So I should push twice?

**Comment by klensy** [comment]
Try manually `git push origin master` to see if it fix the things.
What exact command you use to convert? `./magick mogrify -format png -define png:exclude-chunk=date a-20g.dds` works good. Or send files that fails.

**Comment by gszabi99** [comment]
`MOGRIFY -format png -define png:exclude-chunk=date "D:\WarThunder\datamine\monitor\atlases.vromfs.bin_u\medals\*.dds" > NUL` in a batch script.

**Comment by klensy** [comment]
> 
> 
> `MOGRIFY -format png -define png:exclude-chunk=date "D:\WarThunder\datamine\monitor\atlases.vromfs.bin_u\medals\*.dds" > NUL` in a batch script.

Used this command, all good.
> Version: ImageMagick 7.0.10-14 Q16 x64 2020-05-23

**Comment by gszabi99** [comment]
`Version: ImageMagick 7.0.10-6 016 x64 2020-04-06` Maybe this could be the problem?

**Comment by klensy** [comment]
I really don't know. You can send me files that didn't converted.

**Comment by gszabi99** [comment]
Oooooookay, this problem runs waay deeper than I ever imagined. Tried to manually go through the steps, and of course I ran into a problem. Using the wt-tools_windows-2019/ddsx_unpack.exe (v0.2.2.2), it fails because of the oodle compression type. Which is funny, as literally days ago it had no problem unpacking them.

**Comment by gszabi99** [comment]
Oh wait, I had this problem ages ago. For some reason manually it doesn't work, but if I call it in cmd it does. So it's not a "new" problem, just a forgotten one. :D

**Comment by gszabi99** [comment]
Nope, doesn't want to work even through CMD. Strange, just yesterday it worked without a problem.

**Comment by klensy** [comment]
> 
> 
> Oh wait, I had this problem ages ago. For some reason manually it doesn't work, but if I call it in cmd it does. So it's not a "new" problem, just a forgotten one. :D

Don't work how exactly? There should be some errors printed in console.

**Comment by gszabi99** [comment]
> > Oh wait, I had this problem ages ago. For some reason manually it doesn't work, but if I call it in cmd it does. So it's not a "new" problem, just a forgotten one. :D
> 
> Don't work how exactly? There should be some errors printed in console.

> unsupported compression type: oodle

Very strange, just yesterday it worked flawlessly.

**Comment by klensy** [comment]
And no message about `Can't unpack oodle compressed textures, until ...`?
Try newer version of wt-tools.

**Comment by gszabi99** [comment]
With the newest version: 
![image](https://user-images.githubusercontent.com/45767091/83248151-e8c2a400-a1a4-11ea-85b2-020a8883513e.png)

**Comment by klensy** [comment]
Read the first line please, `Can't unpack oodle compressed textures, until oo2core_6_win64.dll not placed to wt-tools directory`

**Comment by gszabi99** [comment]
But it's there?
![image](https://user-images.githubusercontent.com/45767091/83249080-591df500-a1a6-11ea-88e4-7be339bbb162.png)

**Comment by VitaliiAndreev** [comment]
For me it needs to be where the executable is. In my case an exe I made calls WT Tools and the oodle assembly needs to be with that exe. I don't even have in the WT Tools directory and it works.

**Comment by klensy** [comment]
Reproduced. That error because dll not in PATH from where you launch your bat file. `cd` into wt-tools dir and work from it.

**Comment by gszabi99** [comment]
Thanks. It works once again.

**Comment by klensy** [comment]
It seems like a few people use wt_tools but error reports so rare, even if there actually errors like that.

**Comment by klensy** [comment]
This error with path should be fixed now, but no new build for now.

**Comment by VitaliiAndreev** [comment]
> 
> 
> It seems like a few people use wt_tools but error reports so rare, even if there actually errors like that.

I bet people are mostly interested in _aces.vromfs.bin_ and _char.vromfs.bin_ because stats. Everything else is more niche.

**Comment by klensy** [comment]
So, returning to dds to png convertation, is it works now?

**Comment by klensy** [comment]
Png metadata fixed, as i can see, but there still issues:

It seems that u don't clean folder before unpacking new version, but simply overwrite it: removed files in new version didn't removed in current folder (they simply didn't unpacked and file from old version still here), for example eula_ro.txt last changed long ago, but it added/removed quite often.

**Comment by gszabi99** [comment]
Yes, I did that, and you made me realise how wrong it is. I'm going to modify my script for deletion, and we shall see how it works out.

**Comment by gszabi99** [comment]
It would seem the png problem remains, although on a much smaller scale: [latest commit](https://github.com/gszabi99/War-Thunder-Datamine/commit/bbd0005a22eeff57659fdd83855cc02cf0d4f051)
Any ideas?

**Comment by klensy** [comment]
Somehow `tIME` chunk added, `-format png -define png:exclude-chunk=date,time`

**Comment by gszabi99** [comment]
@klensy It would seem all the issues have been ironed out. Or did I miss something?

**Comment by klensy** [comment]
You forgot to converted dds to png?

**Comment by gszabi99** [comment]
That part of the script did not change, so I don't know what caused it not to function.

**Comment by gszabi99** [comment]
And this time the conversion worked flawlessly! I haven't changed anything... https://github.com/gszabi99/War-Thunder-Datamine/commit/ee32939a6fdeb74c65192600ba141046601dc1fb

**Comment by klensy** [comment]
Try to save logs from all steps (unpacking, mogrifying, etc), there maybe answer.

**Comment by gszabi99** [comment]
I think I fixed it. For some reason MOGRIFY was sometimes buggy with wildcards, so I put it into a for loop and now it runs flawlessly. Hopefully stays this way.

**Comment by klensy** [comment]
You really should split dev and release versions, it's hard to understand changes when all versions mixed together in one history. As you anyway manually checkout previous versions to compare changes.

**Comment by gszabi99** [comment]
Hmm. can you compare two different repos? Because I'd need that for the "Raw changes" when the dev and the live versions are unified once again.

**Comment by klensy** [comment]
If you want, you can create 2 different branches in one repo: 'live' and 'dev' and don't create separate repo.

**Comment by gszabi99** [comment]
I did a thing: https://github.com/gszabi99/War-Thunder-Datamine/branches
Is this what you were thinking?

**Comment by klensy** [comment]
Yes. comparing: https://github.com/gszabi99/War-Thunder-Datamine/compare/master...dev

**Comment by gszabi99** [comment]
This is the live (master branch) script I use, the dev is almost the same except the two masters are swapped out to devs.
![image](https://user-images.githubusercontent.com/45767091/86731944-46fa6680-c030-11ea-8353-a006fd61b3c3.png)

**Comment by klensy** [comment]
I've updated tools so you can check updates without starting game (but maybe except that ones, that downloads when you start the game), plus comparing version (so you know exactly when there is sound update or not), plus download other games version's files w\o downloading entire game.

**Comment by gszabi99** [comment]
Oh nice.

**Comment by gszabi99** [comment]
Using 0.2.2.7, when I try to run `D:\WarThunder\datamine\vromfs_unpacker D:\WarThunder\datamine\UpdateTracker\dev\gui.vromfs.bin` I get the following error:
![image](https://user-images.githubusercontent.com/45767091/89936632-40a17080-dc14-11ea-8a70-e1951b913d9d.png)

**Comment by klensy** [comment]
Yes, i see.

**Comment by klensy** [comment]
Strange, but 0.2.2.6 also fails, but i remember that is worked ok

**Comment by gszabi99** [comment]
Exactly. My first move after panicking was to switch back to 0.2.2.6, but for some reason what worked mere hours ago, doesn't work now.

**Comment by klensy** [comment]
Ahh, vromfs seems updated.

**Comment by klensy** [comment]
Fixed issue, there was file `version`, but this time it was `/version` so it tries to write to absolute path instead of relative, will upload fix.

**Comment by klensy** [comment]
Uploaded, check new version.

**Comment by gszabi99** [comment]
Is there any other way than downloading your entire repo? I assume the release of 0.2.2.7 cannot be updated.

**Comment by klensy** [comment]
Why you download repo instead of [release](https://github.com/klensy/wt-tools/releases)?

**Comment by gszabi99** [comment]
I swear I refreshed the page and it wasn't there. Apologies.

**Comment by gszabi99** [comment]
It indeed works great, nice job!

**Comment by gszabi99** [comment]
Thanks for the tip!
