### ISSUE TITLE
[QUESTION] Where are aircraft speeds located?

### ISSUE THREAD

**Issue by Sgambe33** [gszabi99/War-Thunder-Datamine#10]
Do you guys know where I can find each aircraft speed that is showed inside the game on the vehicle card?

**Comment by gszabi99** [comment]
Aircraft statcard max speeds are in char/unittags, in m/s

**Comment by Sgambe33** [comment]
For tanks and ships it's better to read them from the specific .blkx file?

**Comment by gszabi99** [comment]
Yes.
For ships, it's simple, the `maxSpeed` variable.
For tanks, you need to calculate it from the transmission parameters: `(maxRPM × driveGearRadius) / (mainGearRatio × sideGearRatio × highest gear) × 0.12PI`

**Comment by gszabi99** [comment]
What exactly do you mean by default weapons?

**Comment by Sgambe33** [comment]
For example: 
![image](https://github.com/gszabi99/War-Thunder-Datamine/assets/80386324/eca4fb3d-7d21-43ac-896f-7148d53298b0)
The default 20mm cannon can be found under common weapons if I reckon correctly. However that is not always the case. The F-4C Phantom has by default a 20 GAU cannon but in the blkx is not under common weapons, it's in weapon presets. Is that because in this case the cannon can be swapped with some other weapons so it's not "fixed"?

**Comment by gszabi99** [comment]
Indeed
