### ISSUE TITLE
Line endings

### ISSUE THREAD

**Issue by thisconnected** [gszabi99/War-Thunder-Datamine#11]
some files are using CRLF line endings, some files are using LF (the correct one :heart: ) but that makes comparing between files difficult

You can either fix it by gitatributes or git config

**Comment by OshidaBCF** [comment]
If using winmerge you can also tell it to ignore changes.

**Comment by gszabi99** [comment]
@thisconnected
They *should* all have LF EOLs now.

**Comment by thisconnected** [comment]
this is great! I get a little lazy with my personal one so im relying more and more on your project overtime
