### ISSUE TITLE
Wrong flight models, ships, tanks blk files in vromfs?

### ISSUE THREAD

**Issue by FlxDrv** [gszabi99/War-Thunder-Datamine#14]
The title is kinda missleading but for example, I have the correct, known working, unit file like for the "us_asvhille_class.blk" ship.

The first 5 lines of the blk file look like this:

hasQualityModels:b=yes
model:t="sample_ashville_class"
subclass:t="warShip"
dustFx:t="water_units_dust"
useBotForAi:b=yes

Then why in the unpacked file you share here, the "us_ashville_class.blkx" file looks like this:

  "hasQualityModels": true,
  "model": "ashville_class",
  "subclass": "warShip",
  "dustFx": "water_units_dust",
  "useBotForAi": true,

Is there a way to convert those blkx files into a working blk file? Because as far as i can tell, all the correct data is there, just in a incorrect format right?

I tried to unpack the data myself using WT-Tools but i can't get it working for some reason. Even tho i did manage doing it in the past, a few years ago

Thanks in advance :)

**Comment by TunderTunder** [comment]
same issue

**Comment by gszabi99** [comment]
What you're describing are strict formatted blk files. I don't use strict formatting, as I don't like it. It's not possible to convert non-strict to strict.

**Comment by TunderTunder** [comment]
> What you're describing are strict formatted blk files. I don't use strict formatting, as I don't like it. It's not possible to convert non-strict to strict.

Then how are .blk created in general?  The game uses unreadable characters and those where yes/no is written instead of true/false. And how get it?

**Comment by gszabi99** [comment]
You'd need to unpack the raw files yourself using strict formatting.
