### ISSUE TITLE
Thanks for maintaining this! + Version question

### ISSUE THREAD

**Issue by oenu** [gszabi99/War-Thunder-Datamine#17]
Im working on project that uses war thunder data and your repo is awesome! 

I do have one question though, are the `wpcost` and `shop` file for different versions of the game? It looks like `shop` is for the current release whereas `wpcost` is for the dev branch. I only mention as I have been finding a number of vehicles in `wpcost` that dont exist in `shop` and the ones that do have a different `rank`, which I am only noticing because the game is about to be changed a lot.

If you have any insight I would much appreciate it!

**Comment by Sgambe33** [comment]
No, I believe shop is for the vehicles that you can actually research and buy in game. Wpcost contains all the vehicles that are in the game, both shown and hidden. For example all the UCAVs cannot be bought, they are special vehiles. As a consequence they are not in shop but in wpcost.

**Comment by gszabi99** [comment]
> Im working on project that uses war thunder data and your repo is awesome!

Thank you, and good luck!

> I do have one question though, are the `wpcost` and `shop` file for different versions of the game? It looks like `shop` is for the current release whereas `wpcost` is for the dev branch. I only mention as I have been finding a number of vehicles in `wpcost` that dont exist in `shop` and the ones that do have a different `rank`, which I am only noticing because the game is about to be changed a lot.
> 
> If you have any insight I would much appreciate it!

Think of `wpcost` as the economy data, and `shop` as the tech-tree data. For a researchable/buyable vehicle, you'd need both, but for a vehicle only used in-battle (killstreak drones, nuke bombers, event vehicles, race vehicles, etc.), having only `wpcost` data generally suffices.

**Comment by OshidaBCF** [comment]
If you think that "shop" doesn't look like what you see in game, then i had the same issue a while ago

When gaijin changed (all) folders there was a big difference between live and "Work In Progress" (you can turn that on in the launcher)

As we both use the WiP version there may be slight differences with the normal version
