### ISSUE TITLE
Calculated vehicle parameters

### ISSUE THREAD

**Issue by tprjd** [gszabi99/War-Thunder-Datamine#18]
Hey!

First of all, thanks for maintaining this repo. As I'm looking through the data, I came across a few properties that don't make sense. One of these is "maxSpeed." It is incorrect for all vehicles, and I can't figure out how it is calculated. There are some scripts for the UI, but even after examining those, I couldn't figure it out.
Help would be much appreciated!

Thanks!

**Comment by Sgambe33** [comment]
#10 In this issue gszabi99 pretty much explains everything.

**Comment by tprjd** [comment]
Thank you very much!

**Comment by Sgambe33** [comment]
I saw your website about vehicles stats, nice job. If you need data in a better way than parsing the game files (is a pain in the ass) you can use the API I deployed (images included).

**Comment by OshidaBCF** [comment]
Some variables are "statcards" data, they are usually very wrong or very approximated
