### ISSUE TITLE
atlases.vromfs.bin_u /gameuiskin missing icons

### ISSUE THREAD

**Issue by N00B5T3R** [gszabi99/War-Thunder-Datamine#21]
Hello,

I tried searching the following folder "atlases.vromfs.bin_u /gameuiskin" for the HE icons, but the tree says 
"Sorry, we had to truncate this directory to 1,000 files. 4,537 entries were omitted from the list. Latest commit info may be omitted."
Is there any chance you could please re-add these into the tree?

There are some icons I really really want

**Comment by gszabi99** [comment]
The files are there, that's a limitation of browser GitHub. Downloading the folder should contain every file.

**Comment by N00B5T3R** [comment]
Thank you!

Kinda new to GitHub, I appreciate the help ^_^
