### ISSUE TITLE
Thank you + A Request

### ISSUE THREAD

**Issue by PeterWhitmann** [gszabi99/War-Thunder-Datamine#23]
Hello, before the request I would like to like to send you a big thank you deep in my heart for bringing this data to share public, I have been suffer from this for a couple of month now, and when I found out about this, it solve my problem, and I highly appreciative for your effort that you spent!
But now I have a request for you. Well I having a little bit trouble about the .blkx data infomation, it present in .json format and it can't use ingame, and I don't have too much time to re-edit the whole .blkx beacuse I still have an jobs and this it just my free time things. So could you make it to be suitable to ingame or could you guide me for how to make it work ingame. If you can help me with that, I'm very appreciate.
Forgive me for bad English. But ones again, deep in my heart thank you for making this happen!

**Comment by OshidaBCF** [comment]
your request is the same as this one #24 

you need to download the tool and export it yourself in the game readable format
