### ISSUE TITLE
Совместимость файлов с игрой//Compatibility of files with the game

### ISSUE THREAD

**Issue by naprolom4ik** [gszabi99/War-Thunder-Datamine#24]
Хотел использовать этот репозиторий для создания пользовательской миссии, но не смог из-за того, что файлы "замусорены" квадратными скобками - "[]", фигурными скобками - "{}", отсутствуют типы данных - b, r, i. Хотелось бы, чтою файлы соответствовали тем, что можно найти в папке игры, спасибо

I wanted to use this repository to create a custom mission, but I couldn't because the files are "littered" with square brackets - "[]", curly brackets - "{}", there are no data types - b, r, i. I would like the files to match those that can be found in The game folder, thank you

**Comment by gszabi99** [comment]
I prefer this JSON format, as it's easier to read for me and my scripts are built for it.

**Comment by naprolom4ik** [comment]
OK. Do you know any methods to make the files meet my expectations?

**Comment by OshidaBCF** [comment]
You need to export the files in a different format

we use flare's tool https://github.com/Warthunder-Open-Source-Foundation/wt_ext_cli

`wt_ext_cli unpack_vromf --format BlkText -i .` will loop over all the vromfs files present in the running directory and extract them into game readable files

be sure to check the help message of the tool (`wt_ext_cli unpack_vromf`) for more arguments

**Comment by OshidaBCF** [comment]
the tool export in a readable json format to make it easier to read for us

**Comment by naprolom4ik** [comment]
Where to put commands?

**Comment by OshidaBCF** [comment]
in windows command terminal ?

CMD ?

**Comment by naprolom4ik** [comment]
"wt_ext_cli" is not an internal or external
command, executable program, or batch file.

**Comment by naprolom4ik** [comment]
This created several broken files

**Comment by OshidaBCF** [comment]
either add the tool to the path, or have it in the same folder as the file you want to extract
