### ISSUE TITLE
Enlisted Datamine support ?

### ISSUE THREAD

**Issue by justlookingdontmindme** [gszabi99/War-Thunder-Datamine#6]
Both are published by gaijin and the encodings are the same. Maybe not as demanding as war thunder, but it will please a group of people. I don't think it's very different or difficult. I hope you do some kind of kindness and start supporting it too. Thank you.

**Comment by OshidaBCF** [comment]
I'm bored so i'm answering now

Truth is, we don't hold a lot of interest in Enlisted, if not no interest at all.
I'll put an interesting into it if they ever had something that make me play the game.

Datamining a game i do not play would be very hard just for understanding the values, where as for WT we both have experiences with the game functionalities and stuff.

So for now sorry but i will not datamine Enlisted, except if something interesting start to show up
