### ISSUE TITLE
Use "python3 blk_unpack_ng.py --format=strict_blk" instead of json output

### ISSUE THREAD

**Issue by brokeDude2901** [gszabi99/War-Thunder-Datamine#8]
example:
```python3 blk_unpack_ng.py --format=strict_blk "E:\Games\WarThunder\aces.vromfs.bin_u\gamedata\environments\weather_types.blk"```

**Comment by OshidaBCF** [comment]
The reason the default format is json is that it's far easier to read for us.
The default "blk" format makes it very painful to the eyes for us.

So we will keep the format as it is for now.
