### ISSUE TITLE
[Need help] user profile api calls in unpacked file?

### ISSUE THREAD

**Issue by axiangcoding** [gszabi99/War-Thunder-Datamine#9]
I want to do some data analysis base on player's vehicle profile (like thunderskill.com), but i don't know how to find the related api

Is this repo contains some information can help me acheive that?

best

**Comment by gszabi99** [comment]
Not really, this is more of a data dump.

**Comment by axiangcoding** [comment]
> Not really, this is more of a data dump.

Thanks, I'll find another way
